calibration:
  depth_scale: ''
  focal_px: 117
  img_size:
  - 640
  - 640
  ref_box_norm:
  - 0.6109375
  - 0.409375
  - 0.7375
  - 0.5921875
  ref_distance_m: 2
  ref_height_m: 2
  vertical_vp:
  - 307
  - 1120.25
camera:
  device: 0
  height: 640
  width: 640
gpio:
  active_high: true
  enabled: true
  pin: 17
logging:
  events_file: events.log
model:
  conf_thresh: 0.45
  yolov8_path: models/best.pt
rois:
- - - 0.0375
    - 0.50546875
  - - 0.1859375
    - 0.51015625
  - - 0.234375
    - 0.74296875
  - - 0.028125
    - 0.75859375
thresholds:
  classes_trigger:
  - person
  dwell_time: 2
  height_m: 10
  iou_threshold: 0.002
